export const SEARCH_RESPONSE_TEXT_BUDGET = 12_000;
export const RANKED_SUMMARY_MAX_CHARS = 1_200;
export const RANKED_SUMMARY_MIN_CHARS = 320;
export const MAX_PARALLEL_RESPONSE_RESULTS = 36;
export const MAX_REMAINING_URLS = 20;
